### ISSUE TITLE
loopback-example-ssl not working on remote MySQL, why?

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-connector-mysql#110]
How might I figure out why my local MySQL database instance on XAMPP works with the Loopback Example SSL https://github.com/strongloop/loopback-example-ssl 
while the remote MySQL instance does not?

What variables or settings would be at play?
As far as I can tell, none of the SSL variables that I have found are different for either instance, however, I do not know what specifically to the look for.

The remote MySQL instance, on a GoDaddy reseller shared webhost account, returns this error message:
**Error message**
```javascript
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Handshake inactivity timeout",
    "code": "PROTOCOL_SEQUENCE_TIMEOUT",
    "fatal": true,
    "timeout": 10000,
    "stack": "Error: Handshake inactivity timeout\n    at Handshake.<anonymous> (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Protocol.js:154:17)\n    at Handshake.emit (events.js:104:17)\n    at Handshake._onTimeout (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:116:8)\n    at Timer.listOnTimeout (timers.js:119:15)\n    --------------------\n    at Protocol._enqueue (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Protocol.js:135:48)\n    at Protocol.handshake (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\protocol\\Protocol.js:52:41)\n    at PoolConnection.connect (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\Connection.js:123:18)\n    at Pool.getConnection (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\mysql\\lib\\Pool.js:45:23)\n    at MySQL.executeSQL (c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\lib\\mysql.js:199:12)\n    at c:\\loopback-example-ssl\\node_modules\\loopback-connector-mysql\\node_modules\\loopback-connector\\lib\\sql.js:408:10\n    at c:\\loopback-example-ssl\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:175:9\n    at doNotify (c:\\loopback-example-ssl\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at MySQL.ObserverMixin._notifyBaseObservers (c:\\loopback-example-ssl\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:116:5)\n    at MySQL.ObserverMixin.notifyObserversOf (c:\\loopback-example-ssl\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:91:8)"
  }
}

```
**datasources.json**
```javascript
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "datasourcename": {
  "host": "hostaddress",
  "database": "dbname",
    "username": "dbuser",
    "password": "dbpwd",
    "name": "datasourcename",
    "connector": "mysql"
  }
}
```

**Comment by alexxgathp** [comment]
Investigating is leading me to this, will try it out...
https://github.com/felixge/node-mysql#pool-options

**Comment by alexxgathp** [comment]
I didn't have a chance to test it out completely, but I think that was a possible solution.
What I did instead was switch to a faster MySQL server on Amazon RDS, which solved the timeout issue somehow.
