### ISSUE TITLE
possible EventEmitter memory leak detected on autoupdate (Travis)

### ISSUE THREAD

**Issue by nennad** [strongloop/loopback-connector-mysql#118]
I'm just tried to update my travis infrastructure to use container based instances. Suddenly, autoupdate is failing for one table(5 fields, 6 relations). I get the "(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit." message. On the legacy travis infrastructure everything was fine, but after the update I always get the same problem.

**Comment by raymondfeng** [comment]
Can you find out where (which event emitter) is the warning printed out?

**Comment by nennad** [comment]
The warning comes at when running "loopback_auto:db_autoupdate" (loopback_auto) task
Article (autoupdate)
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:179:15)
    at DataSource.once (events.js:204:8)
    at MySQL.query (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/loopback-connector-mysql/lib/mysql.js:133:28)
    at /home/travis/build/AGCPartners/verusdaat2-api/node_modules/loopback-connector-mysql/lib/mysql.js:712:10
    at /home/travis/build/AGCPartners/verusdaat2-api/node_modules/async/lib/async.js:122:13
    at _each (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/async/lib/async.js:121:9)
    at MySQL.autoupdate (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/loopback-connector-mysql/lib/mysql.js:705:9)
    at DataSource.autoupdate (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/loopback-datasource-juggler/lib/datasource.js:870:18)
    at Object.<anonymous> (/home/travis/build/AGCPartners/verusdaat2-api/node_modules/grunt-loopback-auto/tasks/loopback_auto.js:124:37)

**Comment by raymondfeng** [comment]
That happens when we queue up the operations if the data source is in the process of connecting to the MySQL database.You can wrap your code into something as:
```js
if(myDataSource.connected) {
// Run autoupdate
} else {
  myDataSource.once('connected', function() {
  // Run autoupdate
  });
}
```

**Comment by sklyukin** [comment]
Thx, works for me

**Comment by chiarishow** [comment]
fantastica, worked for me too.

**Comment by jannyHou** [comment]
Closing it since awesome solution provided in https://github.com/strongloop/loopback-connector-mysql/issues/118#issuecomment-129928045 👍
