### ISSUE TITLE
npm test fails with 13 errors

### ISSUE THREAD

**Issue by vserrao** [strongloop/loopback-connector-mysql#148]
Hi,

I've cloned this repo and after running a successful "npm install", running "npm test" gives around 13 errors. Most of them report as : 
Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
or
Uncaught TypeError: Cannot read property 'Inventory' of undefined

Since the issues I'm facing are similar to that raised in #130 issue, I tried the work-around mentioned in it e.g. running the table.sql and creating user "test" with all privileges, configuring test/init.js. However, I noticed that before running "npm test", the tables in strongloop db (generated after executing the table.sql ) are as follows:
mysql> show tables;
+----------------------+
| Tables_in_strongloop |
+----------------------+
| customer             |
| inventory            |
| location             |
| session              |
| weapon               |
+----------------------+

However, after running the "npm test" , the tables are as follows:
mysql> show tables;
+----------------------+
| Tables_in_strongloop |
+----------------------+
| DateData             |
| NestedAddress        |
| NumberData           |
| PostTX               |
| PostWithDefaultId    |
| PostWithStringId     |
| PostWithUniqueTitle  |
| ReviewTX             |
| StringData           |
| TestModel            |
| UserData             |
| UserWithAddress      |
| customer_test        |
+----------------------+

Please let me know the correct MySQL configuration I need to use to run the tests.

Regards,
vserrao

**Comment by rmg** [comment]
I'm seeing multiple failures in the tests as well.

Steps to reproduce on Mac:
 1. `brew install mysql` (leave the default insecure mode, user `root`, no password)
 2. `TEST_MYSQL_USER=root npm test`
 3. 😢 

Unfortunately, loading the schema from `example/table.sql` seems to have no impact on the test results.

Output from a CI environment with MySQL 5.7, since it gives the same results:
```
  1) connections should pass with valid settings:
     Uncaught Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
      at Handshake.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:141:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:136:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:48:16)
      at MySQL.connect (lib/mysql.js:88:17)
      at Object.initializeDataSource [as initialize] (lib/mysql.js:42:28)
      at DataSource.setup (node_modules/loopback-datasource-juggler/lib/datasource.js:337:19)
      at new DataSource (node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
      at Context.<anonymous> (test/mysql.discover.test.js:16:8)

  2) connections ignores all other settings when url is present:
     Uncaught Error: ER_BAD_DB_ERROR: Unknown database 'myapp_test'
      at Handshake.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
      at Handshake.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:141:48)
      at Protocol.handshake (node_modules/mysql/lib/protocol/Protocol.js:52:41)
      at PoolConnection.connect (node_modules/mysql/lib/Connection.js:136:18)
      at Pool.getConnection (node_modules/mysql/lib/Pool.js:48:16)
      at MySQL.connect (lib/mysql.js:88:17)
      at Object.initializeDataSource [as initialize] (lib/mysql.js:42:28)
      at DataSource.setup (node_modules/loopback-datasource-juggler/lib/datasource.js:337:19)
      at new DataSource (node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
      at Context.<anonymous> (test/connection.test.js:42:14)

  3) connections should use utf8 charset:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/connection.test.js:118:12
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:155:34)
      at node_modules/loopback-connector/lib/sql.js:428:7
      at handleResponse (lib/mysql.js:181:17)
      at Query._callback (lib/mysql.js:214:17)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)

  4) connections should drop db and disconnect all:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  

  5) MySQL specific datatypes should fail spectacularly with invalid enum values:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/datatypes.test.js:47:14
      at createCallback (node_modules/loopback-datasource-juggler/lib/dao.js:341:20)
      at node_modules/loopback-connector/lib/sql.js:446:7
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:155:34)
      at node_modules/loopback-connector/lib/sql.js:428:7
      at handleResponse (lib/mysql.js:181:17)
      at Query._callback (lib/mysql.js:192:7)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)

  6) migrations UserData should have correct indexes:

      Uncaught AssertionError: expected Object {
  PRIMARY: RowDataPacket {
    Cardinality: 0,
    Collation: 'A',
    Column_name: 'id',
    Comment: '',
    Index_comment: '',
    Index_type: 'BTREE',
    Key_name: 'PRIMARY',
    Non_unique: 0,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: null,
    Table: 'UserData'
  },
  email: RowDataPacket {
    Cardinality: 0,
    Collation: 'A',
    Column_name: 'email',
    Comment: '',
    Index_comment: '',
    Index_type: 'BTREE',
    Key_name: 'email',
    Non_unique: 1,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: null,
    Table: 'UserData'
  },
  index0: RowDataPacket {
    Cardinality: 0,
    Collation: 'A',
    Column_name: 'email',
    Comment: '',
    Index_comment: '',
    Index_type: 'BTREE',
    Key_name: 'index0',
    Non_unique: 1,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: null,
    Table: 'UserData'
  }
} to equal Object {
  PRIMARY: Object {
    Cardinality: 0,
    Collation: 'A',
    Column_name: 'id',
    Comment: '',
    Index_type: 'BTREE',
    Key_name: 'PRIMARY',
    Non_unique: 0,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: null,
    Table: 'UserData'
  },
  email: Object {
    Cardinality: null,
    Collation: 'A',
    Column_name: 'email',
    Comment: '',
    Index_type: 'BTREE',
    Key_name: 'email',
    Non_unique: 1,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: 333,
    Table: 'UserData'
  },
  index0: Object {
    Cardinality: null,
    Collation: 'A',
    Column_name: 'email',
    Comment: '',
    Index_type: 'BTREE',
    Key_name: 'index0',
    Non_unique: 1,
    Null: '',
    Packed: null,
    Seq_in_index: 1,
    Sub_part: 333,
    Table: 'UserData'
  }
} (at PRIMARY, A has RowDataPacket {
  Cardinality: 0,
  Collation: 'A',
  Column_name: 'id',
  Comment: '',
  Index_comment: '',
  Index_type: 'BTREE',
  Key_name: 'PRIMARY',
  Non_unique: 0,
  Null: '',
  Packed: null,
  Seq_in_index: 1,
  Sub_part: null,
  Table: 'UserData'
} and B has Object {
  Cardinality: 0,
  Collation: 'A',
  Column_name: 'id',
  Comment: '',
  Index_type: 'BTREE',
  Key_name: 'PRIMARY',
  Non_unique: 0,
  Null: '',
  Packed: null,
  Seq_in_index: 1,
  Sub_part: null,
  Table: 'UserData'
})
      + expected - actual

           "Cardinality": 0
           "Collation": "A"
           "Column_name": "id"
           "Comment": ""
      -    "Index_comment": ""
           "Index_type": "BTREE"
           "Key_name": "PRIMARY"
           "Non_unique": 0
           "Null": ""
           "Sub_part": [null]
           "Table": "UserData"
         }
         "email": {
      -    "Cardinality": 0
      +    "Cardinality": [null]
           "Collation": "A"
           "Column_name": "email"
           "Comment": ""
      -    "Index_comment": ""
           "Index_type": "BTREE"
           "Key_name": "email"
           "Non_unique": 1
           "Null": ""
           "Packed": [null]
           "Seq_in_index": 1
      -    "Sub_part": [null]
      +    "Sub_part": 333
           "Table": "UserData"
         }
         "index0": {
      -    "Cardinality": 0
      +    "Cardinality": [null]
           "Collation": "A"
           "Column_name": "email"
           "Comment": ""
      -    "Index_comment": ""
           "Index_type": "BTREE"
           "Key_name": "index0"
           "Non_unique": 1
           "Null": ""
           "Packed": [null]
           "Seq_in_index": 1
      -    "Sub_part": [null]
      +    "Sub_part": 333
           "Table": "UserData"
         }
       }
      
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at test/migration.test.js:83:24
      at test/migration.test.js:437:7
      at node_modules/loopback-datasource-juggler/lib/observer.js:171:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:98:49)
      at MySQL.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:121:5)
      at MySQL.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:96:8)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:161:14)
      at node_modules/loopback-connector/lib/sql.js:428:7
      at handleResponse (lib/mysql.js:181:17)
      at Query._callback (lib/mysql.js:192:7)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
      at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)

  7) migrations should allow numbers with decimals:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/migration.test.js:292:14
      at createCallback (node_modules/loopback-datasource-juggler/lib/dao.js:341:20)
      at node_modules/loopback-connector/lib/sql.js:446:7
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:155:34)
      at node_modules/loopback-connector/lib/sql.js:428:7
      at handleResponse (lib/mysql.js:181:17)
      at Query._callback (lib/mysql.js:192:7)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)

  8) discoverModels Discover database schemas should return an array of db schemas:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  9) discoverModels Discover models including views should return an array of tables and views:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  10) discoverModels Discover current user's tables should return an array of tables for the current user:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  11) discoverModels Discover models excluding views should return an array of only tables:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  12) Discover models including other users should return an array of all tables and views:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  13) Discover model properties Discover a named model should return an array of columns for PRODUCT:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  14) Discover model primary keys should return an array of primary keys for PRODUCT:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
 
  15) Discover model primary keys should return an array of primary keys for STRONGLOOP.PRODUCT:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  16) Discover model foreign keys should return an array of foreign keys for INVENTORY:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  17) Discover model foreign keys should return an array of foreign keys for STRONGLOOP.INVENTORY:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  18) Discover LDL schema from a table should return an LDL schema for INVENTORY:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
  19) Discover and build models should discover and build models:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by dhmlau** [comment]
It seems like the userid that you're using to connect to the database has set only connect from localhost.  You might want to set the hostname of that userid to be '%' (wildcard) or your own machine.  

If you're using MySQL Workbench, go to `Users and Privileges`, modify the `from host` value of the specified userid. 

Reference:
https://dev.mysql.com/doc/refman/5.7/en/problems-connecting.html

**Comment by dhmlau** [comment]
@vserrao, is this good to close? Are you still running into issues?

**Comment by vserrao** [comment]
Currently, I'm working on another high priority task. I will take this up some time later, and reopen the bug if issue still persists. You may close it for now. Thanks!

**Comment by dhmlau** [comment]
Thanks
