### ISSUE TITLE
Fix CI for truncation issue

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-connector-mysql#196]
CI output:

```
  1) migrations should map zero dateTime into null:
     Uncaught AssertionError: expected Error {
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  index: 0,
  sqlState: '22007',
  message: 'ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: \'0000-00-00 00:00:00\' for column \'dateTime\' at row 1'
} to not exist
      at test/migration.test.js:346:20
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:156:34)
      at node_modules/loopback-connector/lib/sql.js:428:7
      at handleResponse (lib/mysql.js:182:17)
      at Query._callback (lib/mysql.js:193:7)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:536:20)
```

See https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-mysql~master/111/consoleFull#-207526304206f8fc75-e0b9-479e-b471-e8fe633361ff

**Comment by superkhau** [comment]
cc @strongloop/fa-db-connectors

**Comment by loay** [comment]
@superkhau That was fixed by by replacing the `null` value by `'1970-01-01';`

**Comment by superkhau** [comment]
Can you link the PR for the fix and close this after? TY.
