### ISSUE TITLE
Returned error when trying to update an id

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-connector-mysql#216]
On this [SO](http://stackoverflow.com/questions/40712784/update-id-value-of-a-model-in-loopback-strongloop/40739314#40739314) post, a user tries to update an ID for a model's instance.
I'm pretty sure this is a terrible idea, and loopback mysql connector returns an error preventing the operation, however the error message is not terribly clear.

`idInjection` is set to true and the `name` property is configured as `id: true`
 
```
PUT http://localhost:3000/api/company/google
{
    "name":"alphabet"
}
```

```
"error": {
    "name": "Error",
    "status": 400,
    "message": "id property (undefined) cannot be updated from undefined to undefined",
    "statusCode": 400,
    "stack":"....etc"
}
```

I suppose when trying to update a model, the connector escapes any ID property, which explained the `undefined` in the error message.

Sounds ok to improve this error message ?

**Comment by superkhau** [comment]
Would you like to submit a PR? That message does look pretty useless.

**Comment by Overdrivr** [comment]
Sure, no problem

**Comment by Overdrivr** [comment]
This is not related to the MySQL connector, I can reproduce it with the memory DB as well. Will look into datasource juggler.

For reference, complete error stack
```
Error: id property (undefined) cannot be updated from undefined to undefined\n    
at ModelConstructor.DataAccessObject.updateAttributes.DataAccessObject.patchAttributes (C:\\loopback-testapp\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:3040:17)\n    
    at SharedMethod.invoke (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\shared-method.js:263:25)\n    
    at HttpContext.invoke (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\http-context.js:389:12)\n    
    at phaseInvoke (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\remote-objects.js:654:9)\n    
    at runHandler (C:\\loopback-testapp\\node_modules\\loopback-phase\\lib\\phase.js:135:5)\n    
    at iterate (C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:146:13)\n    
    at Object.async.eachSeries (C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:162:9)\n    
    at runHandlers (C:\\loopback-testapp\\node_modules\\loopback-phase\\lib\\phase.js:144:13)\n    
    at iterate (C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:146:13)\n    
    at C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:157:25\n    
    at C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:154:25\n    
    at execStack (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\remote-objects.js:493:7)\n    
    at RemoteObjects.execHooks (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\remote-objects.js:497:10)\n    
    at phaseBeforeInvoke (C:\\loopback-testapp\\node_modules\\strong-remoting\\lib\\remote-objects.js:650:10)\n    
    at runHandler (C:\\loopback-testapp\\node_modules\\loopback-phase\\lib\\phase.js:135:5)\n    
    at iterate (C:\\loopback-testapp\\node_modules\\loopback-phase\\node_modules\\async\\lib\\async.js:146:13)
```

**Comment by Overdrivr** [comment]
@superkhau Opened a PR, let me know if you need me to rebase or do some edits ;)

**Comment by superkhau** [comment]
@Overdrivr -- Did a quick review of the PR, thanks for the contribution. ;) I'll let @kjdelisle take it from there as @strongloop/sq-lb-apex is taking care of those repos at this time.

**Comment by dhmlau** [comment]
The corresponding PR (https://github.com/strongloop/loopback-datasource-juggler/pull/1196) has been merged and closed.  Closing this issue.
