### ISSUE TITLE
Bug: discoverSchemas on existing db with foreign keys

### ISSUE THREAD

**Issue by martinlierschof** [strongloop/loopback-connector-mysql#233]
Calling discoverSchemas does not work on a mysql database with existing keys!
When using no foreign keys, it works as expected. The error does not appear and the (table) string are not undefined.

Reproduce Mysql:
```
DROP DATABASE test_foreign;
CREATE DATABASE test_foreign;
USE test_foreign;

CREATE TABLE `TEST_BASE_1` (
  `id` varchar(32) NOT NULL,
  `uuid` varchar(32) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELIMITER $$
CREATE TRIGGER `TEST_BASE_1_extended_insert_id` BEFORE INSERT ON `TEST_BASE_1` FOR EACH ROW BEGIN IF NEW.uuid IS NULL THEN SET NEW.id = REPLACE(UUID(), '-', '');END IF; END;$$
$$
DELIMITER ;

CREATE TABLE `TEST_BASE_2` (
  `id` varchar(32) NOT NULL,
  `uuid` varchar(32) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DELIMITER $$
CREATE TRIGGER `TEST_BASE_2_extended_insert_id` BEFORE INSERT ON `TEST_BASE_2` FOR EACH ROW BEGIN IF NEW.uuid IS NULL THEN SET NEW.id = REPLACE(UUID(), '-', '');END IF; END;$$
$$
DELIMITER ;

CREATE TABLE `TEST_OVER` (
  `id` varchar(32) NOT NULL,
  `id_base_1` varchar(32) NOT NULL,
  `id_base_2` varchar(32) NOT NULL,
  `name` varchar(512) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_base_1) REFERENCES TEST_BASE_1(id),
  FOREIGN KEY (id_base_2) REFERENCES TEST_BASE_2(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

node script:
```
var fs = require('fs');
var loopback = require('loopback');
var app_dir = './';

var app = require('../server');
var dataSource = app.dataSources.myDB;
var db = 'test_foreign', owner = 'root';
function autoGenerateModelFiles() {
  dataSource.discoverModelDefinitions({schema: db}, function (err, models) {
    models.forEach(function (model) {
      dataSource.discoverSchema(currModel.name, {associations: true}, function (err, schema) {
	  });
    });
  });
}
```
will throw following error:
```
XXX\node_modules\mysql\lib\protocol\Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

Error: table is a required string argument: undefined
    at getArgs (XXX\node_modules\loopback-connector-mysql\lib\discovery.js:172:13)
    at MySQL.discoverModelProperties (XXX\node_modules\loopback-connector-mysql\lib\discovery.js:236:16)
    at DataSource.discoverModelProperties (XXX\node_modules\loopback-datasource-juggler\lib\datasource.js:977:20)
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:723:21
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:391:17
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
    at _each (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
    at async.each (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:156:9)
    at _asyncMap (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:390:13)
    at Object.map (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:361:23)
    at _parallel (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:721:20)
    at Object.async.parallel (XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:751:9)
    at DataSource.discoverSchemas (XXX\node_modules\loopback-datasource-juggler\lib\datasource.js:1321:9)
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:723:21
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:391:17
    at XXX\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
```
Versions used:
```
    "compression": "^1.6.2",
    "cors": "^2.8.1",
    "helmet": "^3.4.0",
    "loopback-boot": "^2.23.0",
    "serve-favicon": "^2.3.2",
    "strong-error-handler": "^1.1.1",
    "loopback-component-explorer": "^4.0.0",
    "loopback": "^3.2.0",
    "loopback-connector-mysql": "^3.0.0"
```

**Comment by smartmouse** [comment]
Thank you for your information.  Do you mind forking  the https://github.com/strongloop/loopback-sandbox and place your project files there for us to reproduce? Thank you in advance.

**Comment by martinlierschof** [comment]
Well just use latest installer. Run sql on your mysql database. Configure loopback to mysql database. Run the script with node.

**Comment by martinlierschof** [comment]
Well just use latest installer. Run sql on your mysql database. Configure loopback to mysql database. Run the script with node.

**Comment by ssh24** [comment]
@martinlierschof You are using `currModel.name` for the table name when `currModel` is not defined.

Change your script to:
```
var fs = require('fs');
var loopback = require('loopback');
var app_dir = './';

var app = require('../server');
var dataSource = app.dataSources.myDB;
var db = 'test_foreign', owner = 'root';
function autoGenerateModelFiles() {
  dataSource.discoverModelDefinitions({schema: db}, function (err, models) {
    models.forEach(function (model) {
      dataSource.discoverSchema(model.name, {associations: true}, function (err, schema) {
	  });
    });
  });
}
```

**Comment by ssh24** [comment]
Closing this issue as there has been no update. Feel free to reopen if needed.
