### ISSUE TITLE
I am getting following error randomly when I run try to restart my web. Not able to figure out how can I fix it. Can someone please assist me to resolve this error?

### ISSUE THREAD

**Issue by CoderRathore** [strongloop/loopback-connector-mysql#310]
Hello,

C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\app.js:140
if (err) throw err;
^

Error: connect ETIMEDOUT
at Connection._handleConnectTimeout (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\Connection.js:425:13)
at Socket.g (events.js:291:16)
at emitNone (events.js:86:13)
at Socket.emit (events.js:185:7)
at Socket._onTimeout (net.js:339:8)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)
--------------------
at Protocol._enqueue (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\Protocol.js:141:48)
at Protocol.handshake (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\Protocol.js:52:41)
at Connection.connect (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\Connection.js:136:18)
at getOpenTarget (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\app.js:112:5)
at Query._callback (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\app.js:89:13)
at Query.Sequence.end (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\sequences\Sequence.js:85:24)
at Query._handleFinalResultPacket (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
at Query.EofPacket (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
at Protocol._parsePacket (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\Protocol.js:280:23)
at Parser.write (C:\Users\User\Desktop\20-7-2017\webservice_cron\webservice_cron\webservice\node_modules\mysql\lib\protocol\Parser.js:74:12)

**Comment by ssh24** [comment]
Are you sure your database server is up and running when you start your app? The error looks like it failed to connect to your db server.

**Comment by ssh24** [comment]
Closing this issue due to inactivity. Feel free to reopen if needed.
