### ISSUE TITLE
Loopback process exit if JSON.parse throw error

### ISSUE THREAD

**Issue by phuttipong** [strongloop/loopback-connector-mysql#340]
# Description/Steps to reproduce

From [sandbox](https://github.com/phuttipong/loopback-sandbox/tree/feature/fix_issues_121)
1. run 'setup.mysql.sh' script to create mysql docker container.
2. start loopback by `npm start`
3. goto http://localhost:3000/explorer/#!/message/message_create and POST new message with `{"body":"text"}`
4. open /server/models/message.json and change 'body' property type to 'object'
5. restart loopback
6. goto http://localhost:3000/explorer/#!/message/message_find and click 'try it out' button

then Loopback process will exit and console will show.

```
/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at MySQL.fromColumnValue (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector-mysql/lib/mysql.js:452:22)
    at MySQL.SQLConnector.fromRow.SQLConnector.fromDatabase (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector/lib/sql.js:1414:28)
    at /Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector/lib/sql.js:1446:19
    at Array.map (native)
    at /Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector/lib/sql.js:1445:21
    at /Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:172:22
    at doNotify (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at MySQL.ObserverMixin._notifyBaseObservers (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at MySQL.ObserverMixin.notifyObserversOf (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at cbForWork (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-datasource-juggler/lib/observer.js:162:14)
    at /Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector/lib/sql.js:643:7
    at handleResponse (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector-mysql/lib/mysql.js:193:17)
    at Query._callback (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/loopback-connector-mysql/lib/mysql.js:204:7)
    at Query.Sequence.end (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/Users/phuttipong.aim/Documents/loopback-sandbox/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopback-sandbox@1.0.0 start: `babel-node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-sandbox@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

# Expected result

Loopback process do not exit.

# Additional information

darwin x64 8.1.4

loopback-sandbox@1.0.0 /Users/phuttipong.aim/Documents/loopback-sandbox
├─┬ loopback@2.39.0
│ ├── loopback-connector-remote@1.3.3
│ ├── loopback-context@1.0.0
│ ├── loopback-phase@1.4.1
├─┬ loopback-boot@2.27.0
├─┬ loopback-component-explorer@2.7.0
│ ├── loopback-swagger@2.9.0
├─┬ loopback-connector-mysql@5.2.0
│ ├── loopback-connector@4.4.0
├─┬ loopback-datasource-juggler@2.55.3
│ ├── loopback-connector@2.7.1

**Comment by phuttipong** [comment]
let me post my solution here.

in /lib/sql.js at line 1422
```javascript 
/**
 * Find matching model instances by the filter
 *
 * Please also note the name `all` is confusing. `Model.find` is to find all
 * matching instances while `Model.findById` is to find an instance by id. On
 * the other hand, `Connector.prototype.all` implements `Model.find` while
 * `Connector.prototype.find` implements `Model.findById` due to the `bad`
 * naming convention we inherited from juggling-db.
 *
 * @param {String} model The model name
 * @param {Object} filter The filter
 * @param {Function} [cb] The cb function
 */
SQLConnector.prototype.all = function find(model, filter, options, cb) {
  var self = this;
  // Order by id if no order is specified
  filter = filter || {};
  var stmt = this.buildSelect(model, filter, options);
  this.execute(stmt.sql, stmt.params, options, function(err, data) {
    if (err) {
      return cb(err, []);
    }

   // FIX HERE
    try {
      var objs = data.map(function (obj) {
        return self.fromRow(model, obj);
      });
      if (filter && filter.include) {
        self.getModelDefinition(model).model.include(
          objs, filter.include, options, cb);
      } else {
        cb(null, objs);
      }
    } catch (innerErr) {
      return cb(innerErr, []);
    }
  });
};

```
