### ISSUE TITLE
ER_PARSE_ERROR You have an error in your SQL syntax ; on PATCH Clients/id

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-connector-mysql#343]
# Description/Steps to reproduce

I am facing the error `ER_PARSE_ERROR You have an error in your SQL syntax` when performing a PATCH/PUT `User/{id}` **without any payload**.

To reproduce:
1. Scaffold a loopback app 2.X (Haven't tested in 3.x yet)
2. Add Client extends User
3. Configure a local mysql database (version 5.5)
4. perform the following REST call : `PATCH /api/Clients/:id or PUT /api/Clients/:id` **without any payload**, and observe return code 500

According to the logs, the SQL query in question is the following:
```
UPDATE `Client` SET  WHERE `id`=?, params: [91]
```
I'm no expert but it looks like it's invalid because missing an [assignment list](https://dev.mysql.com/doc/refman/5.7/en/update.html) between SET and WHERE.

This is the error log:

```
2018-01-12T15:30:49.208981+00:00 app[web.1]: 2018-01-12T15:30:49.208Z loopback:connector:mysql SQL: UPDATE `Client` SET  WHERE `id`=?, params: [91]
2018-01-12T15:30:49.215468+00:00 app[web.1]: 2018-01-12T15:30:49.214Z loopback:connector:mysql Error: {"message":"ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id`=91' at line 1","stack":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id`=91' at line 1\n    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)\n    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at TLSSocket.ondata (_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at TLSSocket.Readable.push (_stream_readable.js:134:10)\n    at TLSWrap.onread (net.js:547:20)\n    --------------------\n    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)\n    at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:208:25)\n    at runQuery (/app/node_modules/loopback-connector-mysql/lib/mysql.js:197:16)\n    at executeWithConnection (/app/node_modules/loopback-connector-mysql/lib/mysql.js:239:7)\n    at Ping.onOperationComplete [as _callback] (/app/node_modules/mysql/lib/Pool.js:110:5)\n    at Ping.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)\n    at Ping.Sequence.OkPacket (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)\n    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at TLSSocket.ondata (_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at TLSSocket.Readable.push (_stream_readable.js:134:10)\n    at TLSWrap.onread (net.js:547:20)","code":"ER_PARSE_ERROR","errno":1064,"sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id`=91' at line 1","sqlState":"42000","index":0,"sql":"UPDATE `Client` SET  WHERE `id`=91"}
2018-01-12T15:30:49.215550+00:00 app[web.1]: 2018-01-12T15:30:49.215Z loopback:connector:mysql Data:  undefined
2018-01-12T15:30:49.223831+00:00 app[web.1]: Unhandled error for request PATCH /api/Clients/91: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `id`=91' at line 1
2018-01-12T15:30:49.223833+00:00 app[web.1]:     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
2018-01-12T15:30:49.223834+00:00 app[web.1]:     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2018-01-12T15:30:49.223835+00:00 app[web.1]:     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
2018-01-12T15:30:49.223836+00:00 app[web.1]:     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2018-01-12T15:30:49.223837+00:00 app[web.1]:     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2018-01-12T15:30:49.223838+00:00 app[web.1]:     at TLSSocket.ondata (_stream_readable.js:555:20)
2018-01-12T15:30:49.223839+00:00 app[web.1]:     at emitOne (events.js:96:13)
2018-01-12T15:30:49.223839+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2018-01-12T15:30:49.223840+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2018-01-12T15:30:49.223841+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:134:10)
2018-01-12T15:30:49.223842+00:00 app[web.1]:     at TLSWrap.onread (net.js:547:20)
2018-01-12T15:30:49.223843+00:00 app[web.1]:     --------------------
2018-01-12T15:30:49.223843+00:00 app[web.1]:     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
2018-01-12T15:30:49.223844+00:00 app[web.1]:     at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:208:25)
2018-01-12T15:30:49.223845+00:00 app[web.1]:     at runQuery (/app/node_modules/loopback-connector-mysql/lib/mysql.js:197:16)
2018-01-12T15:30:49.223845+00:00 app[web.1]:     at executeWithConnection (/app/node_modules/loopback-connector-mysql/lib/mysql.js:239:7)
2018-01-12T15:30:49.223846+00:00 app[web.1]:     at Ping.onOperationComplete [as _callback] (/app/node_modules/mysql/lib/Pool.js:110:5)
2018-01-12T15:30:49.223847+00:00 app[web.1]:     at Ping.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
2018-01-12T15:30:49.223848+00:00 app[web.1]:     at Ping.Sequence.OkPacket (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
2018-01-12T15:30:49.223848+00:00 app[web.1]:     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
2018-01-12T15:30:49.223849+00:00 app[web.1]:     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
2018-01-12T15:30:49.223850+00:00 app[web.1]:     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2018-01-12T15:30:49.223850+00:00 app[web.1]:     at TLSSocket.ondata (_stream_readable.js:555:20)
2018-01-12T15:30:49.223851+00:00 app[web.1]:     at emitOne (events.js:96:13)
2018-01-12T15:30:49.223852+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2018-01-12T15:30:49.223852+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2018-01-12T15:30:49.223853+00:00 app[web.1]:     at TLSSocket.Readable.push (_stream_readable.js:134:10)
2018-01-12T15:30:49.223854+00:00 app[web.1]:     at TLSWrap.onread (net.js:547:20)
```

# Link to reproduction sandbox

# Additional information

```
win32 x64 6.11.0
+-- async@2.6.0
+-- bull@3.3.7
+-- chai@4.1.2
+-- compression@1.7.1
+-- cors@2.8.4
+-- debug@3.1.0
+-- dirty-chai@2.0.1
+-- eslint@3.19.0
+-- eslint-config-loopback@8.0.0
+-- google-auto-auth@0.7.2
+-- helmet@3.9.0
+-- ioredis@3.2.2
+-- lodash@4.17.4
+-- loopback@2.39.0
+-- loopback-boot@2.27.0
+-- loopback-component-explorer@2.7.0
+-- loopback-component-storage@3.3.1
+-- loopback-connector-mysql@5.2.0
+-- loopback-datasource-juggler@2.55.3
+-- mocha@3.5.3
+-- moment@2.20.1
+-- nock@9.1.5
+-- nsp@2.8.1
+-- rrule@2.2.0
+-- serve-favicon@2.4.5
+-- sinon@2.4.1
+-- sinon-chai@2.14.0
+-- strong-error-handler@2.3.0
+-- superagent@3.8.2
+-- supertest@3.0.0
+-- uuid@3.1.0
-- validator@9.2.0
```

**Comment by blacktrue** [comment]
I have same problem.

¿Have you fix it?

**Comment by Overdrivr** [comment]
Haven't worked on this yet, but you can easily fix this by implementing a
beforeRemote hook to reject the request if the body is empty.

**Comment by blacktrue** [comment]
@Overdrivr thanks.
