### ISSUE TITLE
Error in hitting queries with LB_LAZYCONNECT_DATASOURCES option as true

### ISSUE THREAD

**Issue by akki-ng** [strongloop/loopback-connector-mysql#345]
Loopback provides an option of lazy connect to datasource by setiing ```LB_LAZYCONNECT_DATASOURCES```.

While the same works on ```loopback-connector-mongo```, but ```loopback-connector-mysql``` gives the error.
```
0|onboardi | Unhandled error for request GET /api/Orders/paginate?access_token=RZisJvfXT4Gfm0SCtUodDpEIvnJaZb5U17S6RKzQ5lulSVVqdUIZ0WcB4mKLibYU: TypeError: Cannot read property 'escapeId' of undefined
0|onboardi |     at MySQL.escapeName (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector-mysql/lib/mysql.js:477:22)
0|onboardi |     at MySQL.SQLConnector.columnEscaped (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector/lib/sql.js:457:15)
0|onboardi |     at /home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector/lib/sql.js:1355:17
0|onboardi |     at Array.map (<anonymous>)
0|onboardi |     at MySQL.SQLConnector.buildColumnNames (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector/lib/sql.js:1354:20)
0|onboardi |     at MySQL.SQLConnector.buildSelect (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector/lib/sql.js:1376:10)
0|onboardi |     at MySQL.find [as all] (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-connector/lib/sql.js:1439:19)
0|onboardi |     at invokeConnectorMethod (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/dao.js:169:21)
0|onboardi |     at /home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/dao.js:2129:7
0|onboardi |     at doNotify (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
0|onboardi |     at doNotify (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
0|onboardi |     at doNotify (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
0|onboardi |     at doNotify (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
0|onboardi |     at Function.ObserverMixin._notifyBaseObservers (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
0|onboardi |     at Function.ObserverMixin.notifyObserversOf (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
0|onboardi |     at Function.ObserverMixin._notifyBaseObservers (/home/akshay/NotInQ/git/onboarding-platform/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)

```

**Comment by akki-ng** [comment]
@dhmlau Any update on this issue and PR?
