### ISSUE TITLE
Pool is closed if datasource.disconnect is called at any point before getConnection

### ISSUE THREAD

**Issue by tmcgee123** [strongloop/loopback-connector-mysql#367]
# Description/Steps to reproduce

1. define a boot script like such that alls the dataSource to disconnect
```
// server/boot/create-lb-tables.js
module.exports = function(server, cb){
    var ds = server.dataSources.ping;
    var lbTables = ['AccessToken', 'ACL', 'RoleMapping', 'Role'];

    ds.autoupdate(lbTables, function(er){
        if (er) throw er;
        console.log('Loopback tables [' + lbTables + '] created in ', ds.adapter.name);
        ds.disconnect();
        cb();
    });
};
```
2. Run application via `node server.js`
3. make login request or run a script that does something with the same datasource
4. see that error is produced
```
2018-11-03T22:17:32.923Z loopback:datasource Datasource localhost: connected=false connecting=false
2018-11-03T22:17:32.923Z loopback:datasource Connecting datasource localhost to connector mysql
2018-11-03T22:17:32.930Z loopback:datasource Datasource localhost is now connected - executing method find
2018-11-03T22:17:32.932Z loopback:datasource Datasource localhost: connected=true connecting=false
2018-11-03T22:17:32.939Z loopback:juggler:utils Sanitizing query object: {"where":{"model":{"inq":["User","*"]},"property":{"inq":["login","*"]},"accessType":{"inq":["EXECUTE","*"]}}}
2018-11-03T22:17:32.947Z loopback:connector:mysql SQL: SELECT `model`,`property`,`accessType`,`permission`,`principalType`,`principalId`,`id` FROM `ACL` WHERE `model` IN (?,?) AND `property` IN (?,?) AND `accessType` IN (?,?) ORDER BY `id`, params: ["User","*","login","*","EXECUTE","*"]
2018-11-03T22:17:32.951Z loopback:connector:sql Error: {} "SELECT `model`,`property`,`accessType`,`permission`,`principalType`,`principalId`,`id` FROM `ACL` WHERE `model` IN (?,?) AND `property` IN (?,?) AND `accessType` IN (?,?) ORDER BY `id`" ["User","*","login","*","EXECUTE","*"]
Error: Pool is closed.
    at /var/www/ping-api/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:26:17
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

# Expected result
I would expect that since the loopback:datasource says it is connected, that the pool would be re-opened. 

# Additional information
After going through the process of finding out how this worked, I realize it might have been able to spot it if the server stopped or something said that the connection was disconnected, instead it made me believe some timeout wasn't long enough or something not code-related. Also, I got the script (although it wasn't suggested to be put in boot) from the main documentation page: https://loopback.io/doc/en/lb3/Creating-a-database-schema-from-models.html
I think a lot of people would use these type of things to do migrations without having to enter the command line. I'm not necessarily proposing that this be fixed, as I know that every team has a limited capacity. But, this just cost me quite a bit of time and I think it's important to note in the docs/logging at least as a best practice to avoid. 

If you absolutely need a reproduction sandbox, I can provide one, but I think that a very explicit insertion in the documentation/logging would likely suffice.

**Comment by pharindoko** [comment]
I can confirm that this issue still exists.

**Comment by b-admike** [comment]
@tmcgee123 @pharindoko Can you try with the latest version `5.4.1`? We've landed @TwistedLogic's fix in #385.

**Comment by tmcgee123** [comment]
@b-admike  Success! Thanks for all of your hard work!

**Comment by b-admike** [comment]
Thank you @tmcgee123 and big thanks for @TwistedLogic who contributed the patch 🎉!
