### ISSUE TITLE
sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client'

### ISSUE THREAD

**Issue by armmmo** [strongloop/loopback-connector-mysql#407]
(node:93125) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Falha de conexão: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
Ela será tentada novamente para a próxima solicitação.
/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
    --------------------
    at Protocol._enqueue (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Pool.js:48:16)
    at MySQL.connect (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-connector-mysql/lib/mysql.js:90:17)
    at Object.initializeDataSource [as initialize] (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-connector-mysql/lib/mysql.js:44:28)
    at DataSource.setup (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-datasource-juggler/lib/datasource.js:502:19)
    at new DataSource (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-datasource-juggler/lib/datasource.js:138:8)
    at Registry.createDataSource (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback/lib/registry.js:364:12)
    at dataSourcesFromConfig (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback/lib/application.js:570:19)
    at Function.app.dataSource (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback/lib/application.js:269:14)
    at /Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-boot/lib/executor.js:191:9
    at /Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-boot/lib/executor.js:282:5
    at Array.forEach (<anonymous>)
    at forEachKeyedObject (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-boot/lib/executor.js:281:20)
    at setupDataSources (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-boot/lib/executor.js:181:3)
Emitted 'error' event on DataSource instance at:
    at DataSource.postInit (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-datasource-juggler/lib/datasource.js:489:16)
    at /Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/loopback-connector-mysql/lib/mysql.js:102:19
    at Handshake.onConnect (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Connection.js:525:10)
    at Handshake._callback (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/Connection.js:491:16)
    at Handshake.Sequence.end (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/Users/usuario/Documents/projects/nodejs/webcars-backend/wbc/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:290:11) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}

**Comment by emonddr** [comment]
@armmmo ,  please provide some more information to help us investigate.

- the version of Node.js you are using
- the version of loopback (3 or 4) you are using
- the dependencies and devDependencies in your package.json
- a small application that demonstrates this problem
- the steps needed to recreate this problem.

Thank you

:)

**Comment by devclickuk** [comment]
This should fix this issue

in mysql run this command with your user name and password

ALTER USER '<USERNAME>'@'localhost' IDENTIFIED WITH mysql_native_password BY '<PASSWORD>'

**Comment by UnKulMunki** [comment]
@devclickuk   That isnt really a fix. that is a downgrade in MySQL password security...
