### ISSUE TITLE
Unable to connect to mysql VPS

### ISSUE THREAD

**Issue by ybarbaria** [strongloop/loopback-connector-mysql#421]
## Steps to reproduce
I am unable to connect my loopback4 api using loopback-connector-mysql.
![image](https://user-images.githubusercontent.com/5574663/83373545-d488dc00-a41c-11ea-9a14-d1a1c212e504.png)

My connection settings : 
`const config = {
  name: 'mysql',
  connector: 'mysql',
  url: '',
  host: '127.0.0.1',
  port: 3306,
  user: 'root',
  password: '******',
  database: 'koala_db',
  connectionLimit: 1000,
  connectTimeout: 60 * 60 * 1000,
  acquireTimeout: 60 * 60 * 1000,
  timeout: 60 * 60 * 1000,
};`

![image](https://user-images.githubusercontent.com/5574663/83373603-174ab400-a41d-11ea-8d2e-fef71ae24a76.png)

![image](https://user-images.githubusercontent.com/5574663/83373689-52e57e00-a41d-11ea-9d54-525980710ab1.png)

## Current Behavior
I have deploying my loopback application with pm2 and I can't connect to mysql.
Mysql is instaled and running on my debian VPS. 

## Expected Behavior
I expect my api will connect to mysql like  when I launch the api on my localhost.

## Additional information
npm -v : 5.8.0
node - v : v10.19.0

linux x64 10.19.0

@loopback/authentication@4.2.5
@loopback/authorization@0.5.10
@loopback/boot@2.3.1
@loopback/context@3.8.1
@loopback/core@2.7.0
@loopback/openapi-v3@3.4.1
@loopback/repository@2.5.1
@loopback/rest@5.0.1
@loopback/rest-explorer@2.2.2
@loopback/service-proxy@2.3.0
@loopback-connector-mysql@5.4.3

**Comment by ybarbaria** [comment]
So I have more information from the logs : 

```
0|KoalaAPI  | Connection fails: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
0|KoalaAPI  | It will be retried for the next request.
0|KoalaAPI  | Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
0|KoalaAPI  |     at Handshake.Sequence._packetToError (/root/production/api/source/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
0|KoalaAPI  |     at Handshake.ErrorPacket (/root/production/api/source/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
0|KoalaAPI  |     at Protocol._parsePacket (/root/production/api/source/node_modules/mysql/lib/protocol/Protocol.js:291:23)
0|KoalaAPI  |     at Parser._parsePacket (/root/production/api/source/node_modules/mysql/lib/protocol/Parser.js:433:10)
0|KoalaAPI  |     at Parser.write (/root/production/api/source/node_modules/mysql/lib/protocol/Parser.js:43:10)
0|KoalaAPI  |     at Protocol.write (/root/production/api/source/node_modules/mysql/lib/protocol/Protocol.js:38:16)
0|KoalaAPI  |     at Socket.<anonymous> (/root/production/api/source/node_modules/mysql/lib/Connection.js:88:28)
0|KoalaAPI  |     at Socket.<anonymous> (/root/production/api/source/node_modules/mysql/lib/Connection.js:526:10)
0|KoalaAPI  |     at Socket.emit (events.js:198:13)
0|KoalaAPI  |     at addChunk (_stream_readable.js:288:12)
0|KoalaAPI  |     at readableAddChunk (_stream_readable.js:269:11)
0|KoalaAPI  |     at Socket.Readable.push (_stream_readable.js:224:10)
0|KoalaAPI  |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
0|KoalaAPI  |     --------------------
0|KoalaAPI  |     at Protocol._enqueue (/root/production/api/source/node_modules/mysql/lib/protocol/Protocol.js:144:48)
0|KoalaAPI  |     at Protocol.handshake (/root/production/api/source/node_modules/mysql/lib/protocol/Protocol.js:51:23)
0|KoalaAPI  |     at PoolConnection.connect (/root/production/api/source/node_modules/mysql/lib/Connection.js:116:18)
0|KoalaAPI  |     at Pool.getConnection (/root/production/api/source/node_modules/mysql/lib/Pool.js:48:16)
0|KoalaAPI  |     at MySQL.connect (/root/production/api/source/node_modules/loopback-connector-mysql/lib/mysql.js:90:17)
0|KoalaAPI  |     at Object.initializeDataSource [as initialize] (/root/production/api/source/node_modules/loopback-connector-mysql/lib/mysql.js:44:28)
0|KoalaAPI  |     at MysqlDataSource.DataSource.setup (/root/production/api/source/node_modules/loopback-datasource-juggler/lib/datasource.js:515:19)
0|KoalaAPI  |     at new DataSource (/root/production/api/source/node_modules/loopback-datasource-juggler/lib/datasource.js:147:8)
0|KoalaAPI  |     at new MysqlDataSource (/root/production/api/source/src/datasources/mysql.datasource.ts:29:5)
0|KoalaAPI  |     at value_promise_1.transformValueOrPromise.args (/root/production/api/source/node_modules/@loopback/context/src/resolver.ts:73:14)
0|KoalaAPI  |     at Object.transformValueOrPromise (/root/production/api/source/node_modules/@loopback/context/src/value-promise.ts:271:12)
0|KoalaAPI  |     at Object.instantiateClass (/root/production/api/source/node_modules/@loopback/context/src/resolver.ts:66:35)
0|KoalaAPI  |     at _setValueGetter (/root/production/api/source/node_modules/@loopback/context/src/binding.ts:741:29)
0|KoalaAPI  |     at Binding._getValue.resolutionCtx [as _getValue] (/root/production/api/source/node_modules/@loopback/context/src/binding.ts:597:14)
0|KoalaAPI  |     at resolution_session_1.ResolutionSession.runWithBinding.s (/root/production/api/source/node_modules/@loopback/context/src/binding.ts:474:2                           3)
0|KoalaAPI  |     at value_promise_1.tryWithFinally (/root/production/api/source/node_modules/@loopback/context/src/resolution-session.ts:122:13)
```

based on this error I have updated my config and create a user called 'api' and I have setup a password for this user. 

Now my config looks like : 
```
{
  "name": "mysql",
  "connector": "mysql",
  "url": "",
  "host": "127.0.0.1",
  "port": 3306,
  "user": "api",
  "password": "********",
  "database": "koala_db",
  "connectionLimit": 1000,
  "connectTimeout": 300000,
  "acquireTimeout": 300000,
  "timeout": 300000
}
```
 and my mysql.datasources.ts : 


```
const config = require('./mysql.datasource.config.json');
@lifeCycleObserver('datasource')
export class MysqlDataSource extends juggler.DataSource
  implements LifeCycleObserver {
  static dataSourceName = 'mysql';
  static readonly defaultConfig = config;

  constructor(
    @inject('datasources.config.mysql', {optional: true})
    dsConfig: object = config,
  ) {
    super(dsConfig);
  }

  stop(): ValueOrPromise<void> {
    return super.disconnect();
  }
}
```



I still have the same issue, I don't understand why the connector doesn't use my configuration. Do you have an idea?

**Comment by dhmlau** [comment]
@ybarbaria, just in case.. did you restart the server after making the changes? Looks like you're trying to connect to the database using user `api` and if there's connection issues, the error should at least complain about user `api` instead of user `root`.

**Comment by ybarbaria** [comment]
@dhmlau Thanks for you feedback, I had and issue with PM2 my last commit wasn't updated, this issues wasn't linked with the connector, sorry about and thanks for your help.
