### ISSUE TITLE
Docs: foreign key order restriction solution is not mentioned

### ISSUE THREAD

**Issue by 0x0aNL** [strongloop/loopback-connector-mysql#443]
## Steps to reproduce

1. Start a new project with MySQL datasource
2. Create two models, e.g. User and Comment
3. On the Comment model, specify a foreign key to User.id
4. Turn on auto-migration with `app.migrateSchema`
5. App will fail to start, as it will try to create a foreign key on Comment to User which does not exist yet
6. Read the documentation: "Note: The order of table creation is important. A referenced table must exist before creating a foreign key constraint."
7. Try to rename model and repository files and/or change the export order in the model/repository index files
8. Ultimately fail to fix the order of table creation as there seemingly is no way to exert control over it

## Current Behavior

Docs currently simply mention that order is important.

The error thrown by the application is:

```
Cannot start the application. Error: ER_CANT_CREATE_TABLE: Can't create table `db`.`Comment` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    --------------------
    at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/usr/src/app/node_modules/mysql/lib/Connection.js:198:25)
    at runQuery (/usr/src/app/node_modules/loopback-connector-mysql/lib/mysql.js:197:16)
    at executeWithConnection (/usr/src/app/node_modules/loopback-connector-mysql/lib/mysql.js:239:7)
    at Ping.onOperationComplete (/usr/src/app/node_modules/mysql/lib/Pool.js:110:5)
    at Ping.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:526:10)
    at Ping._callback (/usr/src/app/node_modules/mysql/lib/Connection.js:488:16)
    at Ping.Sequence.end (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Ping.Sequence.OkPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
    at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20) {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlMessage: 'Can\'t create table `db`.`Comment` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sqlState: 'HY000',
  index: 0,
  sql: 'ALTER TABLE `Comment` ADD  CONSTRAINT `fk_comment_userId` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT',
  statusCode: 500
}
```

## Expected Behavior

Documentation should mention what I luckily stumbled upon: set the order in `app.migrateSchema`.

Example:
```
Note: The order of table creation is important. A referenced table must exist before creating a foreign key constraint.

The order can be specified using the optional SchemaMigrationOptions argument of migrateSchema:

await app.migrateSchema({
      models: [ 'User', 'Comment' ]
});
```

## Additional information
linux x64 14.15.4

+-- @loopback/authentication@7.0.6
+-- @loopback/authentication-jwt@0.7.6
+-- @loopback/authorization@0.7.6
+-- @loopback/boot@3.2.0
+-- @loopback/core@2.14.0
+-- @loopback/health@0.6.3
+-- @loopback/metrics@0.6.0
+-- @loopback/openapi-v3@5.1.3
+-- @loopback/repository@3.4.0
+-- @loopback/rest@9.1.2
+-- @loopback/rest-explorer@3.0.6
+-- @loopback/security@0.3.6
+-- @loopback/service-proxy@3.0.6
+-- loopback-connector-mysql@6.0.0

**Comment by dhmlau** [comment]
@0x0aNL, would you like to submit a PR to improve our docs? Thanks.

**Comment by 0x0aNL** [comment]
@dhmlau [Gave it a whirl](https://github.com/strongloop/loopback-connector-mysql/pull/444) - I hope I correctly followed contribution guidelines.
