### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-mysql#52]
1. Create a simple model attached to a mysql datasource, e.g.
   
   ```
   var Country = loopback.createModel('Country',
     {
       id: { type: 'string', id: true },
       countryName: 'string'
     });
   ```
2. Create an instance of this model.
3. Call `upsert` with the id the instance created in step 2, add extra properties to the JSON payload, e.g.
   
   ``` json
   {
    "id": "id-from-step-2",
    "countryCode": "us",
    "countryName": "USA"
   }
   ```

**Actual result**

`upsert` fails

```
TypeError: Cannot read property 'id' of undefined
    at MySQL.Connector.id (node_modules/loopback-connector-mysql/node_modules/loopback-connector/lib/connector.js:110:11)
    at node_modules/loopback-connector-mysql/lib/mysql.js:239:29
    at Array.forEach (native)
    at MySQL.updateOrCreate.MySQL.save (node_modules/loopback-connector-mysql/lib/mysql.js:238:21)
    at Function.upsert (node_modules/loopback-datasource-juggler/lib/dao.js:224:36)
```

and a trace log is printed to console:

```
Trace: Property not found: Country.countryCode
    at MySQL.Connector.id (node_modules/loopback-connector-mysql/node_modules/loopback-connector/lib/connector.js:108:13)
    at node_modules/loopback-connector-mysql/lib/mysql.js:239:29
    at Array.forEach (native)
    at MySQL.updateOrCreate.MySQL.save (node_modules/loopback-connector-mysql/lib/mysql.js:238:21)
    at Function.upsert (node_modules/loopback-datasource-juggler/lib/dao.js:224:36)
```

**Expected result**

The connector ignores unknown properties and lets the model to decide how to handle them (e.g. depending on the value of the settings `strict`).

See also strongloop/loopback#600.

**Comment by Pentiado** [comment]
Hey!
Is something moving forward with this bug? Couple of days ago I started building an API and my users when creating an account are providing me a name for their Room and that leads to "Trace: Property not found: user.roomName" when in User.afterRemote('create', ...) I try to run verify email method.

**Comment by dallonf** [comment]
Um, this ticket is from 3 months ago and it has a known fix. Why is this still an issue in the latest version?

**Comment by ssh24** [comment]
Can confirm this bug is fixed. Closing this issue.
