### ISSUE TITLE
MySQL connector not compliant with API Gateway

### ISSUE THREAD

**Issue by wascou** [strongloop/loopback-connector-mysql#55]
# Description

There's an issue launching the API Gateway when switched from memory datasource to MySQL datasource and overriding a model.
# Expected Behavior

The server normally launches
#  Steps to reproduce
- Get a fresh loopback-gateway install
- Create a file that overrides the Application model and set it in common/models
- (optional) Do some modification (for example add a dataType text to collaborators)
- Run the server
# Messages

```
~/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1120
    idName = modelTo.dataSource.idName(modelTo.modelName) || 'id';
                                ^
TypeError: Cannot call method 'idName' of null
    at Function.RelationDefinition.belongsTo (~/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1120:33)
    at Function.RelationMixin.belongsTo (~/node_modules/loopback-datasource-juggler/lib/relations.js:123:29)
    at module.exports (~/node_modules/loopback-component-oauth2/lib/models/index.js:26:19)
    at Function.module.exports (~/node_modules/loopback-component-oauth2/lib/oauth2-loopback.js:145:16)
    at Object.<anonymous> (~/server/server.js:36:51)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
# More info

https://groups.google.com/d/msg/loopbackjs/fbXg52tXe-M/5B-xtKEwCVYJ

**Comment by jannyHou** [comment]
@wascou are you still running into same error with API Gateway?
I am not sure how to reproduce it with an API Gateway, but when I followed the chat in https://groups.google.com/d/msg/loopbackjs/fbXg52tXe-M/5B-xtKEwCVYJ it looks like a bug to me(if not been fixed yet.)

**Comment by wascou** [comment]
@jannyHou I guess I can close it as I totally switched my stack. Cheers.
