### ISSUE TITLE
Error: Invalid date on relation request

### ISSUE THREAD

**Issue by Hithim** [strongloop/loopback-connector-mysql#95]
Hello .
I get this error when requesting /api/switches?filter[include]=houses

``` javascript
Error: Invalid date: Invalid Date
    at DateType (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model-builder.js:525:11)
    at ModelConstructor.Object.defineProperty.set [as specActExp] (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model-builder.js:460:81)
    at ModelConstructor.ModelBaseClass._initProperties (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model.js:177:17)
    at ModelConstructor.ModelBaseClass (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model.js:46:8)
    at ModelConstructor (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at ModelConstructor (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at new ModelConstructor (/home/hithim/testo/node_modules/loopback-datasource-juggler/lib/model-builder.js:177:22)
    at /home/hithim/testo/node_modules/loopback-datasource-juggler/lib/include.js:172:48
    at /home/hithim/testo/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
```

there are 2 models switches and houses with relations switches -> has one houses and houses -> has many switches, column specActExp may be NULL .
Maybe someone can tell me what i do wrong.

**Comment by dhmlau** [comment]
@Hithim, sorry to take so long to respond.  Since this problem was reported almost 2 years ago, closing the issue.  If you're still running into this issue, feel free to reopen.  Thanks.
